### ISSUE TITLE
Remote Backing using Ember Data

### ISSUE THREAD

**Issue by gte451f** [toranb/ember-cli-auto-complete#11]
I'm curious does anyone have an idea how they would go about taking the input a user types in and use that to drive a remote ajax query through Ember Data?

I've had some success hacking the suggestion function in my own custom component that extends the auto-complete.   From there I make a call through the store, IE

```
suggestions: function () {
    ...
    store.find('my-model', {filter: my-search-string}); 
```

But I'd like to know the correct place to hook into where I can rebuild the auto-complete options or suggestions property (I don't really understand which one needs to be built).  Is auto complete even promise friendly?

A better approach would be to give the component a list of Ember data models or an Array that is managed by the controller.  The idea is that the auto-complete bubbles up an event that the controller/route catches and updates the list of models.  I can't quite get this approach to work either, I'm not sure where/how to modify the auto-complete to support this approach.

So that's a long way back around to the original question: Does anyone have an idea how they would go about taking the input a user types in and use that to drive a remote ajax query through Ember Data?

**Comment by toranb** [comment]
Just to clarify - you would use this feature to fetch the list of items remotely (using a filter when you hit the server I presume)? Something configurable as you want to limit the number of records coming back /etc?

This would require some research to see what the best implementation in ember looks like (with or without ember-data).

My guess is someone would need to champion the feature / flush out any issues a real app doing this would hit in production. It's on my list but not anywhere near the top priority at this time unfortunately. Help is welcome if you have the bandwidth and need the feature :)

**Comment by gte451f** [comment]
I've had some success building a remote backed auto suggest w/o any modifications to the underlying  component.  

Here is a gist that demonstrates the approach:
https://gist.github.com/gte451f/85d74be8b0bd539a8d19

The key points is that this component modifies the behavior of the auto suggest to first ask the Controller to update the Options array....THEN it asks the component to update the suggestions array.

I am happy to include this in the README if it passes muster.

**Comment by toranb** [comment]
@gte451f wow awesome to see the basic auto complete supports this with a little help from the controller.

I'm all for including something in the readme but if we do I'd like to include a jsbin or link to an example project to help people use it / see that in action. Would either option work for you / be something you'd be willing to help with?

**Comment by toranb** [comment]
@gte451f also I noticed your comment about the "label" being incorrectly documented. If you update the readme, could you include an update to this so the docs aren't broken as you mentioned?

**Comment by gte451f** [comment]
My JSBin Fu isn't very strong, but I'll take a shot sometime in the future.  I'll check out the existing demo and work from that.

**Comment by toranb** [comment]
@gte451f it might be worth creating a demo on this new site (it's ES6 / ember-cli friendly)

http://ember-twiddle.com/

**Comment by mjuniper** [comment]
I took a stab at this too. My approach is based on @gte451f's but with some changes.

The `triggerSuggestions` thing seemed like an unnecessary hack. So I have `suggestions` observe only `options` and I have an `_updateOptions` method that observes `inputVal`. I think this accomplishes the same thing but maybe I'm missing something.

Also, I have the "data access" (just Ember.run.later for purposes of the jsbin) encapsulated inside the component. I get the idea this is not the "ember way" but for my purposes it makes sense. I don't want the controller to have to know anything about where the component gets its data.

http://emberjs.jsbin.com/juxejo/edit?js,output

**Comment by mjuniper** [comment]
Related to this, it seems to me that when using a remote store for suggestions, it would make sense to not have it pop up on focus. `hideWhenNoSuggestions` (which does not seem to be implemented in the version I got from npm) doesn't quite meet this need because we would still want to tell the user, "there are no suggestions for what you typed". Which is different from, "you haven't typed anything (or you've only typed 2 characters) so we are not suggesting anything yet".

**Comment by toranb** [comment]
@mjuniper great point about the suggestions conflict. I should mention that if you are adding this be sure to work off master/ prepare for this to be a 1.0.0 feature (if that's fair for you). If you are busy/we could always ship this as 1.1.0 or later (no rush)

**Comment by toranb** [comment]
@mjuniper @gte451f after months of me neglecting this addon I've decided to give it up :(

I've made the switch to ember-power-select in the last few months and it's worth a look if you need a full featured/yet extensible select component
