### ISSUE TITLE
Doesn't load with ember-cli 0.2.3 or README is inaccurate 

### ISSUE THREAD

**Issue by Floby** [toranb/ember-cli-auto-complete#12]
Hello,

When trying to use this package, ember breaks with this error:

```
Uncaught Error: Could not find module `ember-cli-auto-complete/components/auto-complete` imported from `vision360/components/search-auto-complete`loader.js:110 
```

My component was a straight copy from the README example and it just can't load the base auto-complete component.

What am I missing ?

**Comment by toranb** [comment]
What version of ember are you using? Is this app built using ember-cli or globals? If ember-cli - what version?

**Comment by sebadom** [comment]
I came across this issue too and i'm using ember-cli 0.2.3

**Comment by sebadom** [comment]
i think it uses ember 1.10 and i know that the doc says it should use ember 1.11 for the options template to work, but despite that, the base component should be loaded when extending it and that is the base issue

**Comment by toranb** [comment]
Having a hard time reproducing this w/ ember-cli 0.2.3 because when I npm install it and try "ember new" it blows up. I hear 0.2.4 is in the pipe to fix an army of bugs in 0.2.3. Do you have an example using 0.2.3 that I can do a simple "git pull" to play with myself?

**Comment by sebadom** [comment]
mmmm... i started an empty test app so i could share it with you, but i was able to import the autocomplete with no issues.. so now i'm a bit confused on why i hitted this on the first place... maybe it's a compatibility issue with another ember addon.. i'm just thinking out load... i will investigate a little more and come back with any findings.

thanks

**Comment by toranb** [comment]
And to think I was crazy for not being able to reproduce it myself :)

**Comment by Floby** [comment]
I'll try and make minimal example that reproduces it today

**Comment by toranb** [comment]
@Floby I haven't heard anything in a few months so I'm closing this out for now - let me know if you find another regression :)
