### ISSUE TITLE
Conflicts with main app css

### ISSUE THREAD

**Issue by shripathee** [toranb/ember-cli-auto-complete#14]
```
html {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  line-height: 1.5;
}
```

This especially, and the placeholder and input CSS affect the whole app.

**Comment by toranb** [comment]
Can't disagree with that logic. After reading more about how teams share code with ember-cli addons I'm starting to realize we shouldn't ship custom css ever (it always gets overridden by the people/teams using it).

One work around today -go into your app/index.html and remove the vendor.css entry. This will pull all the css that any addons you are using would normally "add/include"

Long(er) term I think we should simply remove/kill the vendor css that ships with this. When we ship the 0.2.0 or 1.0.0 I'll remove the css file completely.

Sorry for the mess that exists today

**Comment by shripathee** [comment]
I think that is the way to go. Yeah, I found a work around. Super useful add-on though. :+1:

**Comment by toranb** [comment]
I'm closing this out for now but the 1.0 (when released sometime in August) will not ship any css. If you have any issue w/ this decision just let me know :)
