### ISSUE TITLE
Demo crashes browsers

### ISSUE THREAD

**Issue by btecu** [toranb/ember-cli-auto-complete#15]
I haven't tried to debug, but I wanted to see how this works. Unfortunately, both Firefox and Chrome hang when I try to interact with the component on the demo page (http://emberjs.jsbin.com/domuvo/2/).

**Comment by toranb** [comment]
Ah, good catch :)

I'll see if I can update the jsbin tonight (might be a ember beta release that broke it)

**Comment by toranb** [comment]
Just updated it to use ember 1.11.3 in the jsbin and all is working well :)

http://emberjs.jsbin.com/hohegogizi/1/
