### ISSUE TITLE
npm package needs to be updated

### ISSUE THREAD

**Issue by kagemusha** [toranb/ember-cli-auto-complete#21]
seems current npm package doesn't have latest commits

**Comment by toranb** [comment]
Agreed - we are waiting to do a complete v1.0.0 update (checklist mentioned below)

https://github.com/toranb/ember-cli-auto-complete/issues/22

To get what's in master today you can npm install the beta 1 of v1.0.0

```
npm install ember-cli-auto-complete@1.0.0-beta.1
```
