### ISSUE TITLE
Whole page scrolls on keyboard navigation

### ISSUE THREAD

**Issue by jamesarosen** [toranb/ember-cli-auto-complete#24]
When I use the up and down arrows to navigate the suggestions list, the whole window scrolls, not just the list.

See http://stackoverflow.com/questions/11039885/scrollintoview-causing-the-whole-page-to-move

**Comment by jamesarosen** [comment]
One thing that _sort of_ works is

``` js
function keepHighlightInView(event) {
  var highlighted = document.getElementsByClassName("tt-cursor")[0];
  if (highlighted) {
    highlighted.parentNode.scrollTop = highlighted.offsetTop;
  }
}
```

It would be nice to be a bit smarter there and only scroll if it's not in-view.

**Comment by jamesarosen** [comment]
This seems to work pretty well:

``` js
const highlighted = document.getElementsByClassName("tt-cursor")[0];
if (highlighted == null) return;

const parent = highlighted.parentNode;
const needsScroll = (highlighted.offsetTop < parent.scrollTop) ||
                    (highlighted.offsetTop + highlighted.offsetHeight > parent.offsetHeight);

if (needsScroll) {
  highlighted.parentNode.scrollTop = highlighted.offsetTop;
}
```

**Comment by toranb** [comment]
Is this code snippet something we could drop in to prevent this (ie- does it solve your need/keep the component working as-is)?

**Comment by jamesarosen** [comment]
I'll check our app. I'm pretty sure that's what we're using.

**Comment by jamesarosen** [comment]
This is exactly what we're using in our app and it works great.
