### ISSUE TITLE
selectedValue shouldn't write back to its input

### ISSUE THREAD

**Issue by jamesarosen** [toranb/ember-cli-auto-complete#25]
I have something along the lines of

``` hbs
{{#my-autocomplete options=users
                   selectedValue=account.owner.name}}
```

Whenever I type into the autocomplete input, that binding causes `account.owner.name` to be written to. I can work around this with

``` hbs
{{#my-autocomplete options=users
                   selectedValue=(readonly account.owner.name)}}
```

or by creating a new property in `MyAutocomplete`:

``` js
didReceiveAttrs({ attrs }) {
  this.set('selectedValue', Ember.get(attrs, 'selectedText.value'));
}
```

But it would be nice if this library treated that property as input-only and wrote to a private version like `_selectedValue`.

**Comment by toranb** [comment]
It seems like this _selectedValue has come up a few times (other issues anyway). I like the workaround but agree with you that this should be the default (as the goal of this component is to search/select not update the value)
