### ISSUE TITLE
Trouble Writing Acceptance Tests

### ISSUE THREAD

**Issue by jamesarosen** [toranb/ember-cli-auto-complete#26]
Based on https://github.com/toranb/ember-cli-auto-complete/blob/master/tests/acceptance/end-to-end-test.js, I tried the following:

``` js
const DOWN_ARROW = { keyCode: 40 };
const ENTER = { keyCode: 13 };

function selectAutocompleteValue(app, $autocomplete, displayValue) {
  $autocomplete = $($autocomplete);

  if (!$autocomplete.is('input.typeahead')) {
    $autocomplete = $autocomplete.find('input.typeahead');
  }

  if ($autocomplete.length !== 1) {
    throw new Error("selectAutocompleteValue expects exactly one element");
  }

  click($autocomplete);
  fillIn($autocomplete, displayValue);

  for (let i = 0; i < displayValue.length; ++i) {
    triggerEvent($autocomplete, 'keyup', { keyCode: displayValue.charCodeAt(i) });
  }

  triggerEvent($autocomplete, 'keydown', DOWN_ARROW);
  triggerEvent($autocomplete, 'keydown', ENTER);
}

Ember.Test.registerAsyncHelper('selectAutocompleteValue', selectAutocompleteValue);
```

The value in the text field updates, but the action never triggers. Have you written any acceptance tests in apps that use this component?

**Comment by jamesarosen** [comment]
Wrapping the last line in `Ember.run` seems to make the UI do what I expect. So does wrapping the whole function. But the action still doesn't get triggered.

**Comment by jamesarosen** [comment]
Nope. I'm wrong. The action is firing. It's elsewhere my test is failing.

The code above might make a good test helper, though!

**Comment by jamesarosen** [comment]
What finally worked was wrapping the above in

``` js
return Ember.run(function() {
  ...
  return app.testHelpers.wait();
});
```

**Comment by toranb** [comment]
Awesome detail in this issue! I need to have you QA all my ember addons :)
