### ISSUE TITLE
hasInputMatchingSuggestion throws NPE

### ISSUE THREAD

**Issue by jamesarosen** [toranb/ember-cli-auto-complete#27]
https://github.com/toranb/ember-cli-auto-complete/blob/d068282fb522d8ac158d318db54451b991795944/addon/components/auto-complete.js#L111-L118
### Reproduction Steps
1. Create an autocomplete with data and a valid current value
2. Click into the autocomplete. `suggestions` is `null` (because `onInput` hasn't yet fired), so the menu shows empty.
3. Click out of the autocomplete. `suggestions.length` throws a null-pointer exception.

**Comment by jamesarosen** [comment]
I can fix this by calling `this.onInput()` in `didReceiveAttrs`.

**Comment by toranb** [comment]
wow great find! You must be really using this component - finding all my bugs :)

**Comment by toranb** [comment]
Thanks for the repro - I'll write a test and start a PR tonight!

**Comment by jamesarosen** [comment]
You can actually _replace_ the `observes` call with

``` js
didReceiveAttrs() {
  this.onInput();
}
```

**Comment by toranb** [comment]
@jamesarosen so ... are you saying it's a quick fix  (using the didReceiveAttrs line you mentioned) ?

**Comment by jamesarosen** [comment]
I'm 98% sure that removing the `observer` call and adding the lines above is the correct general-purpose fix.

**Comment by toranb** [comment]
Hmm I can't seem to reproduce it in 4200 land or in a test but .. I tried so here is the PR

https://github.com/toranb/ember-cli-auto-complete/pull/28

Would you mind altering the test to show the npe (when you have time)? Thanks again for the epic QA

**Comment by jamesarosen** [comment]
I poked a little. I don't quite have it yet, but here are some notes.

First, the problem only occurs when the autocomplete is initialized with a `selectedValue` that matches one of the elements. Thus,

``` js
return Ember.RSVP.hash({
  model: Bar.create({ code: "AAB" }),
  codes: codes
});
```

Second, the problem only occurs when clicking in and clicking out without typing anything. Thus,

``` js
test("clicking out of the autocomplete will not throw null pointer exception", function (assert) {
  visit("/bar");

  click("input.typeahead");
  andThen(function () {
    assert.equal(find(".tt-dropdown-menu").is(":hidden"), false, "menu is visible");
    assert.equal(find('.tt-suggestion').length, 1, "one suggestion");
  });

  triggerEvent("input.typeahead", "focusOut");
  andThen(function () {
    assert.equal(find(".tt-dropdown-menu").is(":hidden"), true, "menu is hidden");
  });
});
```

But even that doesn't _quite_ do what I want because the first assertion fails, whereas I would expect only the third to.

**Comment by jamesarosen** [comment]
Oh, I'm wrong! It is the third test that's failing. Perfect!

**Comment by jamesarosen** [comment]
My proposed fix doesn't fix that failing test, though. I think it's because the `focusOut` isn't bubbling. I need to trigger it on the autocomplete element itself.

**Comment by jamesarosen** [comment]
When I change `focusOut` to `blur`, the test passes without any code modifications. I suspect the problem lies in my particular subclass of the component -- or rather in the fact that my subclass is incompatible with the existing `observer` approach.

My subclass looks like

``` js
export default AutoComplete.extend({
  didReceiveAttrs({ newAttrs }) {
    // de-promise-ify Ember-Data collections:
    RSVP.resolve(getWithDefault(newAttrs, 'content.value', []))
    .then((content) => { this.set('content', content); });

    // Use a separate property to prevent changes to `selectedValue` from bubbling
    // to the selected object.
    this.set('selectedValue', getWithDefault(newAttrs, 'selectedText.value', ''));

    // fix the bug in this issue:
    this.onInput();
  }
});
```

It might be those `set`s that are conflicting with the `observes`.

**Comment by toranb** [comment]
@jamesarosen sorry for the 9 day hiatus here :(

After a quick followup I had some questions

1) you seem to have this bug still when

  a) you have a selected value (from the model down) (ie- it's provided on render)
  b) you override the base AutoComplete as shown -using a setter (w/out any special ember.run)
  c) you don't call this.onInput() as shown above

2) focusOut (not blur) will show errors in the test you added above so... is this test a good add for the existing suite (showing how authors that extend this might interact with it /help us nail down the funky behavior that seems to be required today to get it working (this.onInput specifically)

**Comment by jamesarosen** [comment]
https://www.youtube.com/watch?v=vvZEddrClAQ @stefanpenner would be happy if you switched from the `observer` solution to `didReceiveAttrs` ;)

I'm not sure what the right test to add for this would be.

**Comment by toranb** [comment]
Totally agreed - just had an observer burn me again this week ....

I'll carve out some time this week to update this as requested :)

**Comment by toranb** [comment]
I finally got around to adding this and like throwing out an observer any day of the week

https://github.com/toranb/ember-cli-auto-complete/pull/28/files

Is the simple implementation I used in the PR fine? Can you/do you want to override it for special ember-data work like you showed above then or ?

This works great @jamesarosen -thanks for pushing us forward!

**Comment by jamesarosen** [comment]
#28 looks awesome. I'm impressed you found a good test for the problem.
