### ISSUE TITLE
Documentation needs to be updated, contains incorrect info

### ISSUE THREAD

**Issue by anthonygore** [toranb/ember-cli-auto-complete#29]
README.md contains incorrect instructions for using the component.

It says you need to implement `determineSuggestions`. I couldn't get it working until I named the function `suggestions` . Also, the `focusOut` function in auto-complete.js will fail unless you also implement `optionsToMatch` in your custom component.

Also, just as a hint to anyone creating a custom component with ember-cli, it will automatically create a template file for your component. This needs to be deleted for the component to work.

**Comment by toranb** [comment]
wow dude so sorry -honestly looks like you just went through the pain of upgrading/using this :(

would you be open to do a PR to update the docs as you suggested? I'd love to hear from a new (fresh) user that knows what's broken/lacking

**Comment by anthonygore** [comment]
Yeah, no probs.
