### ISSUE TITLE
selectedFromList doesn't get reset to false

### ISSUE THREAD

**Issue by jamesarosen** [toranb/ember-cli-auto-complete#30]
As soon as I select a value from the list, `selectedFromList` gets set to `true`. Reopening the list doesn't reset it to `false`. That means that if I
1. click the menu
2. clear the text input
3. select a value
4. click the menu
5. click away

Then the `func` callback will never set `inputVal` and `selectedValue` to `""` any more.

**Comment by toranb** [comment]
great repro setup - I'll dive in this week and see if we can fix this before the 1.0 release!

was this using the latest beta btw ?

**Comment by jamesarosen** [comment]
`"ember-cli-auto-complete": "1.0.0-beta.2",`

**Comment by toranb** [comment]
Awesome -thanks dude!

Next time I plan to release a 1.0 I'll get you on the payroll to find all the issues :)
