### ISSUE TITLE
Cannot customize focusIn, focusOut behavior

### ISSUE THREAD

**Issue by jamesarosen** [toranb/ember-cli-auto-complete#31]
When I focus on an autocomplete that already has a value, it retains the value. That means that the list is prefiltered to exactly one item. It's not obvious to the user that clearing the value would give them more options.

Instead, I suggest
1. keep `selectedValue` as the public API
2. copy `selectedValue` to `_selectedValue` in `didReceiveAttrs`
3. use `_selectedValue` in the display value of the `<input>`
4. set `_selectedValue` to `''` in `focusIn`
5. revert `_selectedValue` to `selectedValue` in the `func` callback in `focusOut` or if the user presses ESC

The one downside to this is that as soon as the user clicks in then they lose the indication of the current value. I think Zendesk does this really well: they show a tooltip with the current value. I don't know that that is a necessary feature for this library, but it might be a nice pattern to support with some documentation.

I can't easily override this behavior in my own subclass because it requires overriding and `focusOut` _without calling `_super`_. That means I can't both override this behavior _and_ get behavior from other mixins.

**Comment by toranb** [comment]
It seems like (outside point of view) that the biggest "broken" feature here is the extensibility of focusOut. 

The opinion about "not obvious to the user" isn't without merit I'm sure but the UX team I worked with as I put this together loved the general defaults provided and felt users learned/or expected this behavior.

about the extension point - if you prefer a different behavior (as you suggested) wouldn't it be fair to assume you'd redefine the behavior (override focusOut/focusIn)?

**Comment by jamesarosen** [comment]
Yes, I think if you moved the callback in focusOut to a public instance method I could pretty easily get the behavior I want.
