### ISSUE TITLE
Menu constrained by overflow

### ISSUE THREAD

**Issue by jamesarosen** [toranb/ember-cli-auto-complete#32]
If I have the following markup:

``` hbs
<div style='overflow: auto;'>
  {{#my-auto-complete options=codes selectedValue=model.code as |result|}}
    <p><b>{{result.code}}</b>{{result.text}}</p>
  {{/my-auto-complete}}
</div>
```

Then the autocomplete menu will be constrained by the `overflow: auto` `<div>`.

The only workaround I can think of is to render the menu somewhere _else_ on the page. [ember-wormhole](https://github.com/yapplabs/ember-wormhole) is good for that. Thus, my recommendation would be
1. add a dependency on `ember-wormhole`
2. add a `<div id="ember-cli-autocomplete-menu"></div>` to the page like [ember-modal-dialog does](https://github.com/yapplabs/ember-modal-dialog/blob/01aa7359371a9bb8bd776672cf9d6d2068663416/addon/initializers/add-modals-container.js#L19-L27)
3. wrap the `.tt-dropdown-menu` in `{{#ember-wormhole}}`
4. somehow change the position and size of the `.tt-dropdown-menu` to match that of the `{{my-auto-complete}}` element, possibly via [Tether](http://github.hubspot.com/tether/)

**Comment by toranb** [comment]
Wow not sure I'm up for a dependency (just yet) on tether. What about some css /style rework here to fix the overflow issue? I only had this on the div for a very simple setup ... maybe it's time we provide a default and optional configuration to override it?

**Comment by jamesarosen** [comment]
The rule is that the `overflow: hidden` (or auto) element must be inside the closest positioned element. Therefore, you'd have to remove the `position: relative` altogether. That means that the menu, which is absolutely positioned, would be relative to an unknown `position: relative` parent.

You could calculate the component's offset and dynamically position the menu relative to it with JS.

There's no CSS solution.

**Comment by toranb** [comment]
The more I think through this issue the more I want to pass you off to a fork :( but because I hate to be a jerk (not supporting you in this effort) I wanted to express "why"

I wrote this addon to be a _very_ simple addon (an alternative to the really robust/complex addons I've seen in the past). I think it's fair to ask that if you need to grow this beyond what I'm willing to maintain/bolt on it would be best as another ember addon - no?

Let me know your thoughts

**Comment by jamesarosen** [comment]
I don't have time to actually maintain a FOSS project -- even a fork. But I could try fixing it in my app and letting you know what hooks might help. For example, it might help to have a `didShowMenu` that is a no-op by default. Or emit an event on the component of the same name.
