### ISSUE TITLE
Cannot use ArrayProxy for suggestions

### ISSUE THREAD

**Issue by jamesarosen** [toranb/ember-cli-auto-complete#36]
https://github.com/toranb/ember-cli-auto-complete/blob/aac91fd0fef3d2af918f57cbd046b993a4dd3cd1/addon/components/auto-complete.js#L101

Should be `.get('suggestions.length')` because `length` is a `ComputedProperty` on `ArrayProxy` objects.

**Comment by toranb** [comment]
Totally cool to change this but what would a test setup look like? I see this and it would appear an ArrayProxy is in the mix -no?

https://github.com/toranb/ember-cli-auto-complete/blob/master/tests/dummy/app/routes/foo.js#L8

**Comment by jamesarosen** [comment]
Easy!

``` js
determineSuggestions() {
  return Ember.ArrayProxy.create({ content: [ 'a', 'b', 'c' ] });
}
```

The reason your existing tests didn't catch it is that your `determineSuggestions` was converting to `Ember.A()`.

**Comment by jamesarosen** [comment]
PS: is there a reason the docs say to override `suggestions` instead of `determineSuggestions`?

``` js
suggestions: function(options, input) {
  var list = options.filter(function(item) {
    return item.get("code").toLowerCase().indexOf(input.toLowerCase()) > -1;
  });
  return Ember.A(list);
}
```

**Comment by toranb** [comment]
@jamesarosen just waiting for a documentation update (thankfully that's coming -note the PR below)

https://github.com/toranb/ember-cli-auto-complete/pull/35#issuecomment-147133129

**Comment by toranb** [comment]
@jamesarosen so I still need to alter this addon for ArrayProxy correct -the documentation point was another issue (solved w/ the docs in 35) -correct?

**Comment by jamesarosen** [comment]
I believe that is correct.
