### ISSUE TITLE
Component Hard-Codes layoutName

### ISSUE THREAD

**Issue by jamesarosen** [toranb/ember-cli-auto-complete#37]
The README states,

> Add a custom component that extends AutoComplete, e.g. with ember-cli:
> `ember generate component my-auto-complete.`
> Note: if you use use ember-cli to generate the component, it will create a template file e.g. my-auto-complete.hbs. Delete this if you don't intend to use it.

In fact, `my-auto-complete.hbs` won't do anything because its parent [specifies](https://github.com/toranb/ember-cli-auto-complete/blob/aac91fd0fef3d2af918f57cbd046b993a4dd3cd1/addon/components/auto-complete.js#L29)

``` js
layoutName: "components/auto-complete",
```

If possible, I suggest removing this manual specification. Otherwise, document that template name.

**Comment by toranb** [comment]
@jamesarosen is this covered via the comment (number 3) in this PR ?

https://github.com/toranb/ember-cli-auto-complete/pull/35#issuecomment-147133129

**Comment by toranb** [comment]
@jamesarosen disregard the previous comment -that's not template/layout related as I originally thought

**Comment by toranb** [comment]
@jamesarosen can we/should we remove this line

```
layoutName: "components/auto-complete"
```

And if so -wouldn't others using it need to specify this? I added this originally because I wanted to keep the "use the addon" api small. Is this a benefit for the "bolt on/ extend" user instead of the "just add it and go" user ?

**Comment by jamesarosen** [comment]
For a component in `app/components/auto-complete.js`, the default template would be in `app/templates/components/auto-complete.hbs`, so I think all you've done is hard-code the default. Unfortunately, hard-coding means subclasses inherit the fixed value rather than the "look up" behavior.
