### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by ghost** [toranb/ember-cli-auto-complete#39]
How can i create Multiple Input from same instance "Repeater or Table". Ex. i will add product list in bill each row should be able to filter products that are in same store.

**Comment by toranb** [comment]
So you need a true multi-select? Honesty this wasn't built with that type of feature set in mind and I've personally been using ember-cli-selectize for my "mutli-select" needs (great addon/easy to acceptance and integration test)

https://github.com/miguelcobain/ember-cli-selectize

**Comment by ghost** [comment]
Great work, thnx for replay. @toranb
