### ISSUE TITLE
Add default suggestions function and optionsToMatch.

### ISSUE THREAD

**Issue by abuiles** [toranb/ember-cli-auto-complete#4]
We could have a generic suggestion and optionsToMatch to make easier for people to migrate for other plugins which use a select like syntax.

I'd like to propose the following API for an out-of-the-box experience

``` hbs
{{auto-complete
  content=codes
  selection=model.code
  optionLabelPath="code"
  optionValuePath=model.code
  prompt="Select code"
}}
```

With this, the suggestions will be filtered based on `optionLabelPath` and assigns the selected value to `optionValuePath`.

**Comment by toranb** [comment]
I assume this ties in nicely w/ the PR you've been cranking away on? I'm not opposed to the idea (haven't worked much w/ the other type ahead components yet myself) and having a glide path for new people is always a plus

**Comment by abuiles** [comment]
@toranb I wrote 2 components on top of this, and I think I like it more simple and let people extend as they want.

**Comment by toranb** [comment]
wow - any of them open source that you can share? I'd love to see how this can play a solid role as the primitive for type aheads :)

**Comment by abuiles** [comment]
@toranb they are closed but I can extract that into an addon, I'm still fleshing out some details, I'll publish once we are done :)
