### ISSUE TITLE
focusOut broken for scrollable lists when document is also scrolled on webkit

### ISSUE THREAD

**Issue by LexLythius** [toranb/ember-cli-auto-complete#42]
If you make the suggestion list scrollable (max-height, overflow-y, etc) and you try to drag the scrollbar button (as opposed to using the mousewheel), the component does the right thing until you scroll the containing document (might also happen with other scrollable containing elements). But once you scroll the document, a focusOut is triggered as soon as you mousedown on the list scrollbar.

If you're on a Mac, you'll have to make sure your system always displays scrollbars--the new default nice self-hiding scrollbars don't do this.

![autocomplete-scrollable1](https://cloud.githubusercontent.com/assets/813204/10923442/a70d7f8a-825f-11e5-98b2-64d846d9801e.png)

Reproducible JSBin: http://emberjs.jsbin.com/qikezo 

1) scroll the document down (you may need to shrink the window).
2) now open the dropdown and try to drag the scrollbar button from the top to the bottom, it will (most likely) close the dropdown.
3) now the weird part: if instead of pointing at the scrollbar button you offset your click as much as you scrolled the whole document, you **won't** get a focusOut, i.e., it's kind of like playing Call of Duty on a crappy network: you aim not for the target you're seeing but for the ghost of the scrollbar where it is supposed to be (had you not scrolled down the document).

![autocomplete-scrollable2](https://cloud.githubusercontent.com/assets/813204/10924078/39d2ea46-8263-11e5-890b-692931b38f3b.png)

Also, document.activeElement is usually the document body, even if clicking on some other element in the DOM.

This happens with webkit browsers, not on Firefox. Didn't test on IE. 
Component version 0.2.1 from NPM repo.
Ember 1.13.8 but it also happens in Ember 1.11.3.

I also tried adding a component of my own to compare and see if this is a general Ember issue but it never triggered focusOut so I can't be sure.

**Comment by toranb** [comment]
Wow this is a great issue w/ jsbin and everything! I don't have a ton of bandwidth for this particular OSS project as of late and I wanted to communicate it in the event you find I'm less responsive than usual :(

I've been playing a lot w/ ember-cli-selectize and the latest "power-select" also to see what I can learn from those projects.
