### ISSUE TITLE
Maybe use ember-list-view

### ISSUE THREAD

**Issue by abuiles** [toranb/ember-cli-auto-complete#5]
We could have some performance gains from this. As soon as it is compatible with the latest Ember it would be worth exploring.

**Comment by toranb** [comment]
The only opinion I have for this component is to keep deps light (for as long as possible anyway). I'm using this internally for a few apps and we've already a ton of pain w/ npm transient dep issues (the upgrade to ember-cli 0.2.0) and I'd like to tread lightly on this one for a bit to avoid any more upgrade pain points

regardless - it's noted :)

**Comment by abuiles** [comment]
Cool, which ember versions are you targeting?

—

**Comment by toranb** [comment]
Right now we are using 1.11 beta 5 (I jumped to 1.11 because components actually work now). Example: the yield out from the component (allowing the easy/nice block param to def your own custom html)

**Comment by toranb** [comment]
Closing this issue for now - if we need this for perf reasons lets reopen / revisit the issue
