### ISSUE TITLE
Don't pollute content with highlight

### ISSUE THREAD

**Issue by abuiles** [toranb/ember-cli-auto-complete#6]
It looks like we are settings 'highlight' in every object passed to the autocomplete, we should find a way to avoid this.

Currently I'm wrapping my objects in a proxy, but that requires extra implementation on consumers end, we could probably create a component to wrap every result and then pass enough context to such component so it knows if it needs  to be highlighted or not.

**Comment by toranb** [comment]
Wow you are a beast man! You cool if I make you a full blown contributor on github and npm? Hate to slow down your epic progress :)

**Comment by abuiles** [comment]
@toranb sounds good :)

**Comment by toranb** [comment]
Just for others who are following along - you are referring to this line (correct?)

https://github.com/toranb/ember-cli-auto-complete/blob/master/addon/components/auto-complete.js#L74

**Comment by bobbyhubbard** [comment]
+1

**Comment by toranb** [comment]
@abuiles can you think of an easier way to work around this / yet show "highlight" in the component (rendred) ? What does this proxy thing you mention look like in practice?

**Comment by jamesarosen** [comment]
One option would be to yield `|item, isHighlighted|`. The other is the [above-mentioned `ObjectProxy`](http://emberjs.com/api/classes/Ember.ObjectProxy.html).

**Comment by jamesarosen** [comment]
This is also a problem because the call is `item.set('highlight', false)` rather than `Ember.set(item, 'highlight', false)`. That requires every item to be an `Ember.Object` instance.
