### ISSUE TITLE
Ember Warning

### ISSUE THREAD

**Issue by gte451f** [toranb/ember-cli-auto-complete#9]
Starting in Ember 1.11 this appears...

WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_warning-when-binding-style-attributes.

Working on a PR to address.

**Comment by toranb** [comment]
fixed in your PR :) thanks again for the heads up!
